# Generated by Django 5.1.4 on 2024-12-17 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='template',
            field=models.CharField(blank=True, default='categories/default.html', max_length=100, null=True, verbose_name='Template'),
        ),
    ]
